# Generated by Django 4.2.7 on 2025-08-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship_coordination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='driller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driller_crews', to='spaceship_coordination.participant'),
        ),
    ]
