# Generated by Django 4.2.7 on 2025-08-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceship_coordination', '0002_alter_crew_driller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='to_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='spaceship_coordination.participant'),
        ),
    ]
